### ISSUE TITLE
Doesn't support IPv6 bridge remote access

### ISSUE THREAD

**Issue by eligrey** [ekux44/LampShade#104]
Bridge remote access works fine for me over IPv4 addresses, but not IPv6 addresses. I do not use port 80 for my bridge, so its public IPv6 address is in the format of `[#:#:#:#:#:::]:port`. I'm guessing that the problem has to do with you incorrectly handling the bracketed IPv6 syntax.

**Comment by ekux44** [comment]
Are you including the brackets in your text input?

As far as I remember, LampShade isn't actually validating the address field and merely storing it as a string, which then gets built into URL's with code such as:

    String url = "http://" + route.address + "/api/" + hash + "/lights";

However there may be some small validation I'm overlooking or I may need to update my networking library dependency. Thanks for the bug report!

**Comment by eligrey** [comment]
Yes, I am including brackets in my text input. Looking at your code I don't see any validation so maybe it's a problem with GsonRequest.

Could you test out GsonRequest with your IPv6 localhost loopback, with and without brackets? The two host strings you will want to test are `::1` and `[::1]:80`.

**Comment by eligrey** [comment]
Oh, so I did some Googling and it may simply be a problem with the Hue bridge and not LampShade.io, as a few search results indicated that the bridge still doesn't fully support IPv6. If your GsonRequest testing turns up fruitless then it's probably the bridge and outside of our control.
