### ISSUE TITLE
Integration with new Hue firmware (April 2016 update)

### ISSUE THREAD

**Issue by srsp** [ekux44/LampShade#108]
It seems that Philips provided a [security update to their Hue bridge in April 2016](http://www2.meethue.com/en-us/support/firmware-update/), which introduces some kind of authorization that breaks integration with LampShade.io.  

So now LampShade.io still discovers the bridge, but it will not notice the push of the button on the bridge. This prevents all users, who already upgraded their bridge from pairing the app with their bridge. Users who paired before the update are fine.

**Comment by halfninja** [comment]
I've forked the project to try and solve this issue, but the author doesn't seem to be responding to anything these past few months so if I get something going it may have to be released as a plain APK or as a separate item in the Store.

**Comment by ekux44** [comment]
After reviewing and smoke-testing the fix, I've cut a new release of LampShade (3.2.3) and pushed it out to beta testing. Expecting to ramp it to all users within the week.
